"""remove timezone-aware constraint

Revision ID: d60bdb665e3d
Revises: 0ceb9da3f85f
Create Date: 2025-08-26 11:31:25.971500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60bdb665e3d'
down_revision: Union[str, Sequence[str], None] = '0ceb9da3f85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
